import './globals.css'
import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import Navbar from '@/components/Navbar'

const redhat = Red_Hat_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='text-white bg-slate-900'>
      <body className={redhat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
